application: bionic-bond-401
version: 1
runtime: php
api_version: 1

handlers:
- url: /setup
  script: api/setup.php
  login: admin
- url: /_ah/mail/.+
  script: api/api.php
- url: /.*
  script: api/api.php

inbound_services:
- mail